name: Run checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    name: Pre-merge checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeLaGuardo/setup-clojure@13
        with:
          bb: latest
          clj-kondo: latest
          cljfmt: latest
      - name: Lint
        run: clj-kondo --lint src views test
      - name: Check formatting
        run: cljfmt check src views test
      - name: Run tests
        run: bb test
